version: '3.8'
services:
  db:
    container_name: template_service_go_db
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5434:5432'
    volumes: 
      - pgdata:/var/lib/postgresql/data
  api:
    container_name: template_service_go_api
    build: 
      context: .
      dockerfile: ./docker/Dockerfile.dev
    volumes:
      - ./:/app
    ports:
      - "4000:4000"
    depends_on:
      - db
networks:
  default:
    name: template_service_go
volumes:
  pgdata: